```{r}
Data<-readxl::read_xlsx("Day_4/Data.xlsx",sheet = "Sheet2")

Data%>%separate(data,sep=" ",into=c("A","B","C","D","E"))


Data<-Data%>%
  mutate(Row=row_number())
bounds<-c(0,Data%>%
  filter(is.na(A))%>%
  pull(Row))
for(i in seq(1,length(bounds)))
{
  DF<-Data%>%filter(Row>bounds[i],Row<bounds[i+1])%>%
    select(-Row)
  assign(value = DF,x =paste0("Hand_",str_pad(i,width = 2,pad = "0")))
}

Calls<-c(13,79,74,35,76,12,43,71,87,72,23,91,31,67,58,61,96,16,81,92,41,6,32,86,77,42,0,55,68,14,53,26,25,11,45,94,75,1,93,83,52,7,4,22,34,64,69,88,65,66,39,97,27,29,78,5,49,82,54,46,51,28,98,36,48,15,2,50,38,24,89,59,8,3,18,47,10,90,21,80,73,33,85,62,19,37,57,95,60,20,99,17,63,56,84,44,40,70,9,30)

```
Part1
```{r}
for(i in seq(1,length(Calls)))
{
 for (j in seq(1,99))
 {
   Current_hand<-get(paste0("Hand_",str_pad(j,width = 2,pad = "0")))
   Current_hand_matrix<-as.matrix(Current_hand)
   Current_hand_matrix[Current_hand_matrix == Calls[i]] <- -1
   if (sum(Current_hand_matrix[1,])==-5|sum(Current_hand_matrix[2,])==-5|sum(Current_hand_matrix[3,])==-5|sum(Current_hand_matrix[4,])==-5| sum(Current_hand_matrix[5,])==-5|sum(Current_hand_matrix[,1])==-5| sum(Current_hand_matrix[,2])==-5| sum(Current_hand_matrix[,3])==-5|sum(Current_hand_matrix[,4])==-5| sum(Current_hand_matrix[,5])==-5)
   {
print(Calls[i])
print(Current_hand_matrix)
print(sum(Current_hand_matrix[Current_hand_matrix!=-1]))
print(paste("Answer: ",Calls[i]*sum(Current_hand_matrix[Current_hand_matrix!=-1])))
  stop()
}
   Current_hand<-as.data.frame(Current_hand_matrix)
   
   assign(value = Current_hand,x =paste0("Hand_",str_pad(j,width = 2,pad = "0")))
   
 }
}
```


```{r}
Finished<-c()
for(i in seq(1,length(Calls)))
{
 for (j in seq(1,99))
   if (!j %in% Finished)
   {
 {
   Current_hand<-get(paste0("Hand_",str_pad(j,width = 2,pad = "0")))
   Current_hand_matrix<-as.matrix(Current_hand)
   Current_hand_matrix[Current_hand_matrix == Calls[i]] <- -1
   if (sum(Current_hand_matrix[1,])==-5|sum(Current_hand_matrix[2,])==-5|sum(Current_hand_matrix[3,])==-5|sum(Current_hand_matrix[4,])==-5| sum(Current_hand_matrix[5,])==-5|sum(Current_hand_matrix[,1])==-5| sum(Current_hand_matrix[,2])==-5| sum(Current_hand_matrix[,3])==-5|sum(Current_hand_matrix[,4])==-5| sum(Current_hand_matrix[,5])==-5)
   {
Finished<-c(Finished,j)
if(length(Finished)==99)
{
  print(j)
  print(Current_hand_matrix)

print(paste("Answer: ",Calls[i]*sum(Current_hand_matrix[Current_hand_matrix!=-1])))  
  stop()
}
   }
   Current_hand<-as.data.frame(Current_hand_matrix)
   
   assign(value = Current_hand,x =paste0("Hand_",str_pad(j,width = 2,pad = "0")))
   
 }
   }
}
```

