```{r}
Raw_data<-readxl::read_xlsx("Data.xlsx")

Data<-Raw_data%>%separate(header,into=c(letters[1:11]),sep = "",remove = T)%>%select(-a)%>%mutate(across(.fns = as.numeric))%>%as.matrix()

```
Part2

```{r}
Flashed=0
print(Data)
for(i in seq(1,100))
{
Data=Data+1
#print(Data)

Flashed<-Flashed+length(Data[which(Data==10)])

a<-sort(adjacent(raster(Data),which(Data==10),directions=8)[,2])
a<-a[which(Data[a]!=10)]
Data[which(Data>=10)]=NA
while(length(a)>0)
{
for (j in seq(1,length(a)))
{
Data[a[j]]=Data[a[j]]+1
}
Data
Flashed<-Flashed+length(Data[which(Data>=10)])
a<-sort(adjacent(raster(Data),which(Data>=10),directions=8)[,2])
a<-a[which(Data[a]<10)]
Data[which(Data>=10)]=NA
}
Data[which(is.na(Data))]=0
}
Flashed

```


Part1
```{r}
Flashed=0
print(Data)
i=0
while(sum(Data)!=0)
{
  i=i+1
Data=Data+1
#print(Data)

Flashed<-Flashed+length(Data[which(Data==10)])

a<-sort(adjacent(raster(Data),which(Data==10),directions=8)[,2])
a<-a[which(Data[a]!=10)]
Data[which(Data>=10)]=NA
while(length(a)>0)
{
for (j in seq(1,length(a)))
{
Data[a[j]]=Data[a[j]]+1
}
Data
Flashed<-Flashed+length(Data[which(Data>=10)])
a<-sort(adjacent(raster(Data),which(Data>=10),directions=8)[,2])
a<-a[which(Data[a]<10)]
Data[which(Data>=10)]=NA
}
Data[which(is.na(Data))]=0
}
i

```
